name: Build and Push Docker images

on:
  push:
    branches:
      - develop_part2  # gałąź do automatycznego builda

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build and push APP image
      - name: Build app Docker image
        run: docker build -t alandocke/nodejs2025q2-service:latest -f Dockerfile .

      - name: Push app Docker image
        run: docker push alandocke/nodejs2025q2-service:latest

      # Build and push DB image
      - name: Build database Docker image
        run: docker build -t alandocke/nodejs2025q2-db:latest -f Dockerfile.postgres .

      - name: Push database Docker image
        run: docker push alandocke/nodejs2025q2-db:latest
